import type { Registry } from "./schema";

export const registry: Registry = [
  {
    name: "utils",
    type: "registry:lib",
    dependencies: ["clsx", "tailwind-merge"],
    files: [{ path: "lib/utils.ts", type: "registry:lib" }],
  },
  {
    name: "icons",
    type: "registry:lib",
    files: [
      { path: "icons/icon-base.tsx", type: "registry:lib" },
      { path: "icons/add.tsx", type: "registry:lib" },
      { path: "icons/calendar.tsx", type: "registry:lib" },
      { path: "icons/check.tsx", type: "registry:lib" },
      { path: "icons/chevron-down.tsx", type: "registry:lib" },
      { path: "icons/chevron-right.tsx", type: "registry:lib" },
      { path: "icons/chevron-up.tsx", type: "registry:lib" },
      { path: "icons/eye.tsx", type: "registry:lib" },
      { path: "icons/eye-off.tsx", type: "registry:lib" },
      { path: "icons/lock.tsx", type: "registry:lib" },
      { path: "icons/mail.tsx", type: "registry:lib" },
      { path: "icons/minus.tsx", type: "registry:lib" },
      { path: "icons/search.tsx", type: "registry:lib" },
    ],
  },
  {
    name: "button",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    registryDependencies: ["utils"],
    files: [{ path: "components/button.tsx", type: "registry:ui" }],
  },
  {
    name: "input",
    type: "registry:ui",
    registryDependencies: ["utils", "icons"],
    files: [{ path: "components/input.tsx", type: "registry:ui" }],
  },
  {
    name: "textarea",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{ path: "components/textarea.tsx", type: "registry:ui" }],
  },
  {
    name: "label",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-label"],
    registryDependencies: ["utils"],
    files: [{ path: "components/label.tsx", type: "registry:ui" }],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-checkbox"],
    registryDependencies: ["utils"],
    files: [{ path: "components/checkbox.tsx", type: "registry:ui" }],
  },
  {
    name: "switch",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-switch"],
    registryDependencies: ["utils"],
    files: [{ path: "components/switch.tsx", type: "registry:ui" }],
  },
  {
    name: "select",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-select"],
    registryDependencies: ["utils", "icons"],
    files: [{ path: "components/select.tsx", type: "registry:ui" }],
  },
  {
    name: "radio",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-radio-group"],
    registryDependencies: ["utils"],
    files: [{ path: "components/radio.tsx", type: "registry:ui" }],
  },
  {
    name: "slider",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-slider"],
    registryDependencies: ["utils"],
    files: [{ path: "components/slider.tsx", type: "registry:ui" }],
  },
  {
    name: "toggle",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-toggle"],
    registryDependencies: ["utils"],
    files: [{ path: "components/toggle.tsx", type: "registry:ui" }],
  },
  {
    name: "otp-input",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{ path: "components/otp-input.tsx", type: "registry:ui" }],
  },
  {
    name: "date-picker",
    type: "registry:ui",
    registryDependencies: ["utils", "button", "popover", "icons"],
    files: [{ path: "components/date-picker.tsx", type: "registry:ui" }],
  },
  {
    name: "card",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{ path: "components/card.tsx", type: "registry:ui" }],
  },
  {
    name: "separator",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-separator"],
    registryDependencies: ["utils"],
    files: [{ path: "components/separator.tsx", type: "registry:ui" }],
  },
  {
    name: "scroll-area",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-scroll-area"],
    registryDependencies: ["utils"],
    files: [{ path: "components/scroll-area.tsx", type: "registry:ui" }],
  },
  {
    name: "table",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{ path: "components/table.tsx", type: "registry:ui" }],
  },
  {
    name: "tabs",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-tabs"],
    registryDependencies: ["utils"],
    files: [{ path: "components/tabs.tsx", type: "registry:ui" }],
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-slot"],
    registryDependencies: ["utils"],
    files: [{ path: "components/breadcrumb.tsx", type: "registry:ui" }],
  },
  {
    name: "pagination",
    type: "registry:ui",
    registryDependencies: ["utils", "button"],
    files: [{ path: "components/pagination.tsx", type: "registry:ui" }],
  },
  {
    name: "dialog",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-dialog"],
    registryDependencies: ["utils"],
    files: [{ path: "components/dialog.tsx", type: "registry:ui" }],
  },
  {
    name: "sheet",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-dialog"],
    registryDependencies: ["utils"],
    files: [{ path: "components/sheet.tsx", type: "registry:ui" }],
  },
  {
    name: "popover",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-popover"],
    registryDependencies: ["utils"],
    files: [{ path: "components/popover.tsx", type: "registry:ui" }],
  },
  {
    name: "dropdown-menu",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-dropdown-menu"],
    registryDependencies: ["utils", "icons"],
    files: [{ path: "components/dropdown-menu.tsx", type: "registry:ui" }],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-tooltip"],
    registryDependencies: ["utils"],
    files: [{ path: "components/tooltip.tsx", type: "registry:ui" }],
  },
  {
    name: "toast",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-toast"],
    registryDependencies: ["utils"],
    files: [{ path: "components/toast.tsx", type: "registry:ui" }],
  },
  {
    name: "progress",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-progress"],
    registryDependencies: ["utils"],
    files: [{ path: "components/progress.tsx", type: "registry:ui" }],
  },
  {
    name: "accordion",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-accordion"],
    registryDependencies: ["utils", "icons"],
    files: [{ path: "components/accordion.tsx", type: "registry:ui" }],
  },
  {
    name: "avatar",
    type: "registry:ui",
    dependencies: ["@radix-ui/react-avatar"],
    registryDependencies: ["utils"],
    files: [{ path: "components/avatar.tsx", type: "registry:ui" }],
  },
  {
    name: "badge",
    type: "registry:ui",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["utils"],
    files: [{ path: "components/badge.tsx", type: "registry:ui" }],
  },
];
