const ACTIONS = ["Read", "Create", "Update", "Delete", "Import", "Export", "Print"] as const;

const resource = (module: string, feature: string) =>
  [`${module}.${feature}.*`, ...ACTIONS.map((a) => `${module}.${feature}.${a}`)] as const;

export const PERMISSIONS = [
  "*",
  "Overview.*",
  ...resource("Overview", "Overview"),
  "HR.*",
  ...resource("HR", "Employees"),
  ...resource("HR", "ExpenseClaims"),
  ...resource("HR", "Attritions"),
  ...resource("HR", "Sanctions"),
  ...resource("HR", "Onboarding"),
  ...resource("HR", "Offboarding"),
  ...resource("HR", "Promotions"),
  ...resource("HR", "Transfers"),
  ...resource("HR", "Separations"),
  ...resource("HR", "DisciplinaryReports"),
  ...resource("HR", "Organogram"),
  ...resource("HR", "Branches"),
  ...resource("HR", "Departments"),
  ...resource("HR", "Units"),
  ...resource("HR", "JobRoles"),
  ...resource("HR", "EmploymentTypes"),
  ...resource("HR", "EmployeeGrades"),
  ...resource("HR", "HolidayList"),
  ...resource("HR", "LeaveTypes"),
  ...resource("HR", "LeavePolicies"),
  ...resource("HR", "WorkSchedules"),
  ...resource("HR", "PersonalDetails"),
  "Leave.*",
  ...resource("Leave", "LeaveCalendar"),
  ...resource("Leave", "LeavePlans"),
  ...resource("Leave", "LeaveAllocations"),
  ...resource("Leave", "LeaveApplications"),
  ...resource("Leave", "Resumptions"),
  "Performance.*",
  ...resource("Performance", "ReviewCycles"),
  ...resource("Performance", "Feedback360"),
  ...resource("Performance", "GoalsAndOKRs"),
  ...resource("Performance", "NineBoxGrid"),
  ...resource("Performance", "DevelopmentPlans"),
  ...resource("Performance", "AnalyticsAndReports"),
  "Payroll.*",
  ...resource("Payroll", "PayrollEntry"),
  ...resource("Payroll", "SalarySlips"),
  ...resource("Payroll", "AdditionalSalary"),
  ...resource("Payroll", "SalaryRegister"),
  ...resource("Payroll", "BankRemittance"),
  ...resource("Payroll", "TaxDeductions"),
  ...resource("Payroll", "PensionReport"),
  ...resource("Payroll", "SalaryComponents"),
  ...resource("Payroll", "SalaryStructures"),
  ...resource("Payroll", "StructureAssignments"),
  ...resource("Payroll", "PayrollPeriods"),
  ...resource("Payroll", "IncomeTaxSlabs"),
  ...resource("Payroll", "TaxConfiguration"),
  "Recruitment.*",
  ...resource("Recruitment", "Jobs"),
  ...resource("Recruitment", "Candidates"),
  ...resource("Recruitment", "PipelineStages"),
  ...resource("Recruitment", "RecruitmentAnalytics"),
  ...resource("Recruitment", "TalentPool"),
  ...resource("Recruitment", "InterviewTypes"),
  ...resource("Recruitment", "OfferTemplates"),
  ...resource("Recruitment", "AppointmentTemplates"),
  ...resource("Recruitment", "JobTemplates"),
  "Finance.*",
  ...resource("Finance", "JournalEntries"),
  ...resource("Finance", "PaymentEntries"),
  ...resource("Finance", "SalesInvoices"),
  ...resource("Finance", "PurchaseInvoices"),
  ...resource("Finance", "BankReconciliation"),
  ...resource("Finance", "TrialBalance"),
  ...resource("Finance", "ProfitAndLoss"),
  ...resource("Finance", "BalanceSheet"),
  ...resource("Finance", "CashFlow"),
  ...resource("Finance", "ConsolidatedView"),
  ...resource("Finance", "ARAgeing"),
  ...resource("Finance", "APAgeing"),
  ...resource("Finance", "SalesRegister"),
  ...resource("Finance", "PurchaseRegister"),
  ...resource("Finance", "ChartOfAccounts"),
  ...resource("Finance", "FiscalYear"),
  ...resource("Finance", "CostCenters"),
  ...resource("Finance", "AccountingPeriods"),
  ...resource("Finance", "PaymentTerms"),
  ...resource("Finance", "BanksAndAccounts"),
  ...resource("Finance", "TaxRules"),
  ...resource("Finance", "Currencies"),
  ...resource("Finance", "TransactionRates"),
  "Budget.*",
  ...resource("Budget", "BudgetProposals"),
  ...resource("Budget", "BudgetManagement"),
  ...resource("Budget", "ApprovedBudgets"),
  ...resource("Budget", "DepartmentBudgetView"),
  ...resource("Budget", "ExpenseManagement"),
  ...resource("Budget", "ExtraBudgetary"),
  ...resource("Budget", "ApprovalSettings"),
  ...resource("Budget", "BudgetVarianceReport"),
  ...resource("Budget", "CostCentres"),
  "Loans.*",
  ...resource("Loans", "LoanApplications"),
  ...resource("Loans", "Loans"),
  ...resource("Loans", "LoanDisbursement"),
  ...resource("Loans", "LoanRepayments"),
  ...resource("Loans", "LoanReports"),
  ...resource("Loans", "InterestAccrual"),
  ...resource("Loans", "WriteOff"),
  ...resource("Loans", "LoanTypes"),
  "Assets.*",
  ...resource("Assets", "Assets"),
  ...resource("Assets", "MaintenanceRequests"),
  ...resource("Assets", "MaintenanceSchedule"),
  ...resource("Assets", "AssetMovement"),
  ...resource("Assets", "DepreciationLedger"),
  ...resource("Assets", "AssetLifecycle"),
  ...resource("Assets", "MaintenanceReport"),
  ...resource("Assets", "AssetCategories"),
  ...resource("Assets", "Locations"),
  ...resource("Assets", "DepreciationMethods"),
  ...resource("Assets", "MaintenanceTeams"),
  "Procurement.*",
  ...resource("Procurement", "PurchaseRequests"),
  ...resource("Procurement", "PurchaseOrders"),
  ...resource("Procurement", "Suppliers"),
  ...resource("Procurement", "Vendors"),
  ...resource("Procurement", "RFQs"),
  ...resource("Procurement", "PurchaseAnalytics"),
  ...resource("Procurement", "POAnalysis"),
  ...resource("Procurement", "VendorScorecard"),
  ...resource("Procurement", "VendorGroups"),
  ...resource("Procurement", "ApprovalThresholds"),
  ...resource("Procurement", "BuyingSettings"),
  "Inventory.*",
  ...resource("Inventory", "StockEntries"),
  ...resource("Inventory", "PurchaseReceipts"),
  ...resource("Inventory", "DeliveryNotes"),
  ...resource("Inventory", "StockReconciliation"),
  ...resource("Inventory", "StockLedger"),
  ...resource("Inventory", "StockBalance"),
  ...resource("Inventory", "ReorderAlerts"),
  ...resource("Inventory", "StockAgeing"),
  ...resource("Inventory", "Items"),
  ...resource("Inventory", "ItemGroups"),
  ...resource("Inventory", "Warehouses"),
  ...resource("Inventory", "UnitsOfMeasure"),
  "CRM.*",
  ...resource("CRM", "Leads"),
  ...resource("CRM", "Opportunities"),
  ...resource("CRM", "Customers"),
  ...resource("CRM", "Contacts"),
  ...resource("CRM", "Contracts"),
  ...resource("CRM", "SalesFunnel"),
  ...resource("CRM", "LeadAnalytics"),
  ...resource("CRM", "CRMAnalytics"),
  ...resource("CRM", "LeadSources"),
  ...resource("CRM", "CustomerGroups"),
  ...resource("CRM", "Territories"),
  ...resource("CRM", "SalesPersons"),
  "Sales.*",
  ...resource("Sales", "Quotations"),
  ...resource("Sales", "SalesOrders"),
  ...resource("Sales", "SalesInvoices"),
  ...resource("Sales", "DeliveryNotes"),
  ...resource("Sales", "Commissions"),
  ...resource("Sales", "SalesAnalytics"),
  ...resource("Sales", "SalesOrderAnalysis"),
  ...resource("Sales", "TerritoryVariance"),
  ...resource("Sales", "PriceLists"),
  ...resource("Sales", "PricingRules"),
  "Users.*",
  ...resource("Users", "Users"),
  ...resource("Users", "UserGroups"),
  ...resource("Users", "Delegations"),
  ...resource("Users", "Roles"),
  ...resource("Users", "RoleProfiles"),
  ...resource("Users", "PermissionManager"),
  ...resource("Users", "AuditLog"),
  ...resource("Users", "LoginHistory"),
  "System.*",
  ...resource("System", "Organization"),
  ...resource("System", "Workflows"),
  ...resource("System", "SecurityPolicy"),
  ...resource("System", "IPRestrictions"),
  ...resource("System", "TwoFAAndSSO"),
  ...resource("System", "EmailSMTP"),
  ...resource("System", "NotificationTemplates"),
  ...resource("System", "SequenceSettings"),
  ...resource("System", "CustomFields"),
  ...resource("System", "PrintFormats"),
  ...resource("System", "Webhooks"),
  ...resource("System", "DataImport"),
  ...resource("System", "SystemAuditLog"),
  ...resource("System", "DataBackup"),
  ...resource("System", "ScheduledJobs"),
];
