export const ACCESS_LEVELS = [
  { label: "Own", value: "own" },
  { label: "Unit", value: "unit" },
  { label: "Department", value: "department" },
  { label: "Organization", value: "organization" },
];

export const ISOLATION_MODES = [
  { label: "Shared", value: "Shared" },
  { label: "Dedicated", value: "Dedicated" },
];

export const COMPANY_SIZE = [
  { label: "1-10", value: "1-10" },
  { label: "11-50", value: "11-50" },
  { label: "51-200", value: "51-200" },
  { label: "201-500", value: "201-500" },
  { label: "501-1000", value: "501-1000" },
  { label: "1001-5000", value: "1001-5000" },
  { label: "5001-10000", value: "5001-10000" },
  { label: "10000+", value: "10000+" },
];

export const DATE_FORMATS = [
  { label: "MM/dd/yyyy", value: "MM/dd/yyyy" },
  { label: "dd/MM/yyyy", value: "dd/MM/yyyy" },
  { label: "yyyy-MM-dd", value: "yyyy-MM-dd" },
  { label: "dd MMM yyyy", value: "dd MMM yyyy" },
  { label: "MMM dd, yyyy", value: "MMM dd, yyyy" },
];

export const INDUSTRIES = [
  { label: "Technology", value: "technology" },
  { label: "Healthcare", value: "healthcare" },
  { label: "Finance", value: "finance" },
  { label: "Education", value: "education" },
  { label: "Retail", value: "retail" },
  { label: "Manufacturing", value: "manufacturing" },
  { label: "Real Estate", value: "real_estate" },
  { label: "Agriculture", value: "agriculture" },
  { label: "Energy", value: "energy" },
  { label: "Transportation", value: "transportation" },
  { label: "Telecommunications", value: "telecommunications" },
  { label: "Media & Entertainment", value: "media_entertainment" },
  { label: "Hospitality", value: "hospitality" },
  { label: "Construction", value: "construction" },
  { label: "Insurance", value: "insurance" },
  { label: "Legal Services", value: "legal_services" },
  { label: "Pharmaceuticals", value: "pharmaceuticals" },
  { label: "Automotive", value: "automotive" },
  { label: "Nonprofit", value: "nonprofit" },
  { label: "Government", value: "government" },
];

export const DEFAULT_LANGUAGES = [
  { label: "English", value: "english" },
  { label: "French", value: "french" },
  { label: "Spanish", value: "spanish" },
  { label: "German", value: "german" },
  { label: "Italian", value: "italian" },
  { label: "Portuguese", value: "portuguese" },
  { label: "Russian", value: "russian" },
  { label: "Chinese", value: "chinese" },
  { label: "Japanese", value: "japanese" },
  { label: "Arabic", value: "arabic" },
  { label: "Hindi", value: "hindi" },
  { label: "Swahili", value: "swahili" },
];

export const TIME_ZONES = [
  { label: "UTC (UTC+0)", value: "UTC" },
  { label: "GMT (UTC+0)", value: "GMT" },
  { label: "London (UTC+0/+1)", value: "Europe/London" },
  { label: "Lagos (UTC+1)", value: "Africa/Lagos" },
  { label: "Nairobi (UTC+3)", value: "Africa/Nairobi" },
  { label: "Dubai (UTC+4)", value: "Asia/Dubai" },
  { label: "Mumbai (UTC+5:30)", value: "Asia/Kolkata" },
  { label: "Singapore (UTC+8)", value: "Asia/Singapore" },
  { label: "Tokyo (UTC+9)", value: "Asia/Tokyo" },
  { label: "Sydney (UTC+10/+11)", value: "Australia/Sydney" },
  { label: "New York (UTC-5/-4)", value: "America/New_York" },
  { label: "Chicago (UTC-6/-5)", value: "America/Chicago" },
  { label: "Denver (UTC-7/-6)", value: "America/Denver" },
  { label: "Los Angeles (UTC-8/-7)", value: "America/Los_Angeles" },
  { label: "São Paulo (UTC-3)", value: "America/Sao_Paulo" },
];

export const DIAL_CODES = [
  { label: "Afghanistan", value: "+93", code: "AF" },
  { label: "Aland Islands", value: "+358", code: "AX" },
  { label: "Albania", value: "+355", code: "AL" },
  { label: "Algeria", value: "+213", code: "DZ" },
  { label: "AmericanSamoa", value: "+1684", code: "AS" },
  { label: "Andorra", value: "+376", code: "AD" },
  { label: "Angola", value: "+244", code: "AO" },
  { label: "Anguilla", value: "+1264", code: "AI" },
  { label: "Antarctica", value: "+672", code: "AQ" },
  { label: "Antigua and Barbuda", value: "+1268", code: "AG" },
  { label: "Argentina", value: "+54", code: "AR" },
  { label: "Armenia", value: "+374", code: "AM" },
  { label: "Aruba", value: "+297", code: "AW" },
  { label: "Australia", value: "+61", code: "AU" },
  { label: "Austria", value: "+43", code: "AT" },
  { label: "Azerbaijan", value: "+994", code: "AZ" },
  { label: "Bahamas", value: "+1242", code: "BS" },
  { label: "Bahrain", value: "+973", code: "BH" },
  { label: "Bangladesh", value: "+880", code: "BD" },
  { label: "Barbados", value: "+1246", code: "BB" },
  { label: "Belarus", value: "+375", code: "BY" },
  { label: "Belgium", value: "+32", code: "BE" },
  { label: "Belize", value: "+501", code: "BZ" },
  { label: "Benin", value: "+229", code: "BJ" },
  { label: "Bermuda", value: "+1441", code: "BM" },
  { label: "Bhutan", value: "+975", code: "BT" },
  { label: "Bolivia, Plurinational State of", value: "+591", code: "BO" },
  { label: "Bosnia and Herzegovina", value: "+387", code: "BA" },
  { label: "Botswana", value: "+267", code: "BW" },
  { label: "Brazil", value: "+55", code: "BR" },
  { label: "British Indian Ocean Territory", value: "+246", code: "IO" },
  { label: "Brunei Darussalam", value: "+673", code: "BN" },
  { label: "Bulgaria", value: "+359", code: "BG" },
  { label: "Burkina Faso", value: "+226", code: "BF" },
  { label: "Burundi", value: "+257", code: "BI" },
  { label: "Cambodia", value: "+855", code: "KH" },
  { label: "Cameroon", value: "+237", code: "CM" },
  { label: "Canada", value: "+1", code: "CA" },
  { label: "Cape Verde", value: "+238", code: "CV" },
  { label: "Cayman Islands", value: "+ 345", code: "KY" },
  { label: "Central African Republic", value: "+236", code: "CF" },
  { label: "Chad", value: "+235", code: "TD" },
  { label: "Chile", value: "+56", code: "CL" },
  { label: "China", value: "+86", code: "CN" },
  { label: "Christmas Island", value: "+61", code: "CX" },
  { label: "Cocos (Keeling) Islands", value: "+61", code: "CC" },
  { label: "Colombia", value: "+57", code: "CO" },
  { label: "Comoros", value: "+269", code: "KM" },
  { label: "Congo", value: "+242", code: "CG" },
  { label: "Congo, The Democratic Republic of the Congo", value: "+243", code: "CD" },
  { label: "Cook Islands", value: "+682", code: "CK" },
  { label: "Costa Rica", value: "+506", code: "CR" },
  { label: "Cote d'Ivoire", value: "+225", code: "CI" },
  { label: "Croatia", value: "+385", code: "HR" },
  { label: "Cuba", value: "+53", code: "CU" },
  { label: "Cyprus", value: "+357", code: "CY" },
  { label: "Czech Republic", value: "+420", code: "CZ" },
  { label: "Denmark", value: "+45", code: "DK" },
  { label: "Djibouti", value: "+253", code: "DJ" },
  { label: "Dominica", value: "+1767", code: "DM" },
  { label: "Dominican Republic", value: "+1849", code: "DO" },
  { label: "Ecuador", value: "+593", code: "EC" },
  { label: "Egypt", value: "+20", code: "EG" },
  { label: "El Salvador", value: "+503", code: "SV" },
  { label: "Equatorial Guinea", value: "+240", code: "GQ" },
  { label: "Eritrea", value: "+291", code: "ER" },
  { label: "Estonia", value: "+372", code: "EE" },
  { label: "Ethiopia", value: "+251", code: "ET" },
  { label: "Falkland Islands (Malvinas)", value: "+500", code: "FK" },
  { label: "Faroe Islands", value: "+298", code: "FO" },
  { label: "Fiji", value: "+679", code: "FJ" },
  { label: "Finland", value: "+358", code: "FI" },
  { label: "France", value: "+33", code: "FR" },
  { label: "French Guiana", value: "+594", code: "GF" },
  { label: "French Polynesia", value: "+689", code: "PF" },
  { label: "Gabon", value: "+241", code: "GA" },
  { label: "Gambia", value: "+220", code: "GM" },
  { label: "Georgia", value: "+995", code: "GE" },
  { label: "Germany", value: "+49", code: "DE" },
  { label: "Ghana", value: "+233", code: "GH" },
  { label: "Gibraltar", value: "+350", code: "GI" },
  { label: "Greece", value: "+30", code: "GR" },
  { label: "Greenland", value: "+299", code: "GL" },
  { label: "Grenada", value: "+1473", code: "GD" },
  { label: "Guadeloupe", value: "+590", code: "GP" },
  { label: "Guam", value: "+1671", code: "GU" },
  { label: "Guatemala", value: "+502", code: "GT" },
  { label: "Guernsey", value: "+44", code: "GG" },
  { label: "Guinea", value: "+224", code: "GN" },
  { label: "Guinea-Bissau", value: "+245", code: "GW" },
  { label: "Guyana", value: "+595", code: "GY" },
  { label: "Haiti", value: "+509", code: "HT" },
  { label: "Holy See (Vatican City State)", value: "+379", code: "VA" },
  { label: "Honduras", value: "+504", code: "HN" },
  { label: "Hong Kong", value: "+852", code: "HK" },
  { label: "Hungary", value: "+36", code: "HU" },
  { label: "Iceland", value: "+354", code: "IS" },
  { label: "India", value: "+91", code: "IN" },
  { label: "Indonesia", value: "+62", code: "ID" },
  { label: "Iran, Islamic Republic of Persian Gulf", value: "+98", code: "IR" },
  { label: "Iraq", value: "+964", code: "IQ" },
  { label: "Ireland", value: "+353", code: "IE" },
  { label: "Isle of Man", value: "+44", code: "IM" },
  { label: "Israel", value: "+972", code: "IL" },
  { label: "Italy", value: "+39", code: "IT" },
  { label: "Jamaica", value: "+1876", code: "JM" },
  { label: "Japan", value: "+81", code: "JP" },
  { label: "Jersey", value: "+44", code: "JE" },
  { label: "Jordan", value: "+962", code: "JO" },
  { label: "Kazakhstan", value: "+77", code: "KZ" },
  { label: "Kenya", value: "+254", code: "KE" },
  { label: "Kiribati", value: "+686", code: "KI" },
  { label: "Korea, Democratic People's Republic of Korea", value: "+850", code: "KP" },
  { label: "Korea, Republic of South Korea", value: "+82", code: "KR" },
  { label: "Kuwait", value: "+965", code: "KW" },
  { label: "Kyrgyzstan", value: "+996", code: "KG" },
  { label: "Laos", value: "+856", code: "LA" },
  { label: "Latvia", value: "+371", code: "LV" },
  { label: "Lebanon", value: "+961", code: "LB" },
  { label: "Lesotho", value: "+266", code: "LS" },
  { label: "Liberia", value: "+231", code: "LR" },
  { label: "Libyan Arab Jamahiriya", value: "+218", code: "LY" },
  { label: "Liechtenstein", value: "+423", code: "LI" },
  { label: "Lithuania", value: "+370", code: "LT" },
  { label: "Luxembourg", value: "+352", code: "LU" },
  { label: "Macao", value: "+853", code: "MO" },
  { label: "Macedonia", value: "+389", code: "MK" },
  { label: "Madagascar", value: "+261", code: "MG" },
  { label: "Malawi", value: "+265", code: "MW" },
  { label: "Malaysia", value: "+60", code: "MY" },
  { label: "Maldives", value: "+960", code: "MV" },
  { label: "Mali", value: "+223", code: "ML" },
  { label: "Malta", value: "+356", code: "MT" },
  { label: "Marshall Islands", value: "+692", code: "MH" },
  { label: "Martinique", value: "+596", code: "MQ" },
  { label: "Mauritania", value: "+222", code: "MR" },
  { label: "Mauritius", value: "+230", code: "MU" },
  { label: "Mayotte", value: "+262", code: "YT" },
  { label: "Mexico", value: "+52", code: "MX" },
  { label: "Micronesia, Federated States of Micronesia", value: "+691", code: "FM" },
  { label: "Moldova", value: "+373", code: "MD" },
  { label: "Monaco", value: "+377", code: "MC" },
  { label: "Mongolia", value: "+976", code: "MN" },
  { label: "Montenegro", value: "+382", code: "ME" },
  { label: "Montserrat", value: "+1664", code: "MS" },
  { label: "Morocco", value: "+212", code: "MA" },
  { label: "Mozambique", value: "+258", code: "MZ" },
  { label: "Myanmar", value: "+95", code: "MM" },
  { label: "Namibia", value: "+264", code: "NA" },
  { label: "Nauru", value: "+674", code: "NR" },
  { label: "Nepal", value: "+977", code: "NP" },
  { label: "Netherlands", value: "+31", code: "NL" },
  { label: "Netherlands Antilles", value: "+599", code: "AN" },
  { label: "New Caledonia", value: "+687", code: "NC" },
  { label: "New Zealand", value: "+64", code: "NZ" },
  { label: "Nicaragua", value: "+505", code: "NI" },
  { label: "Niger", value: "+227", code: "NE" },
  { label: "Nigeria", value: "+234", code: "NG" },
  { label: "Niue", value: "+683", code: "NU" },
  { label: "Norfolk Island", value: "+672", code: "NF" },
  { label: "Northern Mariana Islands", value: "+1670", code: "MP" },
  { label: "Norway", value: "+47", code: "NO" },
  { label: "Oman", value: "+968", code: "OM" },
  { label: "Pakistan", value: "+92", code: "PK" },
  { label: "Palau", value: "+680", code: "PW" },
  { label: "Palestinian Territory, Occupied", value: "+970", code: "PS" },
  { label: "Panama", value: "+507", code: "PA" },
  { label: "Papua New Guinea", value: "+675", code: "PG" },
  { label: "Paraguay", value: "+595", code: "PY" },
  { label: "Peru", value: "+51", code: "PE" },
  { label: "Philippines", value: "+63", code: "PH" },
  { label: "Pitcairn", value: "+872", code: "PN" },
  { label: "Poland", value: "+48", code: "PL" },
  { label: "Portugal", value: "+351", code: "PT" },
  { label: "Puerto Rico", value: "+1939", code: "PR" },
  { label: "Qatar", value: "+974", code: "QA" },
  { label: "Romania", value: "+40", code: "RO" },
  { label: "Russia", value: "+7", code: "RU" },
  { label: "Rwanda", value: "+250", code: "RW" },
  { label: "Reunion", value: "+262", code: "RE" },
  { label: "Saint Barthelemy", value: "+590", code: "BL" },
  { label: "Saint Helena, Ascension and Tristan Da Cunha", value: "+290", code: "SH" },
  { label: "Saint Kitts and Nevis", value: "+1869", code: "KN" },
  { label: "Saint Lucia", value: "+1758", code: "LC" },
  { label: "Saint Martin", value: "+590", code: "MF" },
  { label: "Saint Pierre and Miquelon", value: "+508", code: "PM" },
  { label: "Saint Vincent and the Grenadines", value: "+1784", code: "VC" },
  { label: "Samoa", value: "+685", code: "WS" },
  { label: "San Marino", value: "+378", code: "SM" },
  { label: "Sao Tome and Principe", value: "+239", code: "ST" },
  { label: "Saudi Arabia", value: "+966", code: "SA" },
  { label: "Senegal", value: "+221", code: "SN" },
  { label: "Serbia", value: "+381", code: "RS" },
  { label: "Seychelles", value: "+248", code: "SC" },
  { label: "Sierra Leone", value: "+232", code: "SL" },
  { label: "Singapore", value: "+65", code: "SG" },
  { label: "Slovakia", value: "+421", code: "SK" },
  { label: "Slovenia", value: "+386", code: "SI" },
  { label: "Solomon Islands", value: "+677", code: "SB" },
  { label: "Somalia", value: "+252", code: "SO" },
  { label: "South Africa", value: "+27", code: "ZA" },
  { label: "South Sudan", value: "+211", code: "SS" },
  { label: "South Georgia and the South Sandwich Islands", value: "+500", code: "GS" },
  { label: "Spain", value: "+34", code: "ES" },
  { label: "Sri Lanka", value: "+94", code: "LK" },
  { label: "Sudan", value: "+249", code: "SD" },
  { label: "Suriname", value: "+597", code: "SR" },
  { label: "Svalbard and Jan Mayen", value: "+47", code: "SJ" },
  { label: "Swaziland", value: "+268", code: "SZ" },
  { label: "Sweden", value: "+46", code: "SE" },
  { label: "Switzerland", value: "+41", code: "CH" },
  { label: "Syrian Arab Republic", value: "+963", code: "SY" },
  { label: "Taiwan", value: "+886", code: "TW" },
  { label: "Tajikistan", value: "+992", code: "TJ" },
  { label: "Tanzania, United Republic of Tanzania", value: "+255", code: "TZ" },
  { label: "Thailand", value: "+66", code: "TH" },
  { label: "Timor-Leste", value: "+670", code: "TL" },
  { label: "Togo", value: "+228", code: "TG" },
  { label: "Tokelau", value: "+690", code: "TK" },
  { label: "Tonga", value: "+676", code: "TO" },
  { label: "Trinidad and Tobago", value: "+1868", code: "TT" },
  { label: "Tunisia", value: "+216", code: "TN" },
  { label: "Turkey", value: "+90", code: "TR" },
  { label: "Turkmenistan", value: "+993", code: "TM" },
  { label: "Turks and Caicos Islands", value: "+1649", code: "TC" },
  { label: "Tuvalu", value: "+688", code: "TV" },
  { label: "Uganda", value: "+256", code: "UG" },
  { label: "Ukraine", value: "+380", code: "UA" },
  { label: "United Arab Emirates", value: "+971", code: "AE" },
  { label: "United Kingdom", value: "+44", code: "GB" },
  { label: "United States", value: "+1", code: "US" },
  { label: "Uruguay", value: "+598", code: "UY" },
  { label: "Uzbekistan", value: "+998", code: "UZ" },
  { label: "Vanuatu", value: "+678", code: "VU" },
  { label: "Venezuela, Bolivarian Republic of Venezuela", value: "+58", code: "VE" },
  { label: "Vietnam", value: "+84", code: "VN" },
  { label: "Virgin Islands, British", value: "+1284", code: "VG" },
  { label: "Virgin Islands, U.S.", value: "+1340", code: "VI" },
  { label: "Wallis and Futuna", value: "+681", code: "WF" },
  { label: "Yemen", value: "+967", code: "YE" },
  { label: "Zambia", value: "+260", code: "ZM" },
  { label: "Zimbabwe", value: "+263", code: "ZW" },
];

// #region ARBITRARY FORM OPTIONS

export const TITLES = [
  { label: "Mr.", value: "mr" },
  { label: "Mrs.", value: "mrs" },
  { label: "Miss", value: "miss" },
  { label: "Dr.", value: "dr" },
  { label: "Prof.", value: "prof" },
];

export const GENDERS = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
];

export const MARITAL_STATUSES = [
  { label: "Single", value: "single" },
  { label: "Married", value: "married" },
  { label: "Divorced", value: "divorced" },
  { label: "Widowed", value: "widowed" },
];

export const RELATIONSHIPS = [
  { label: "Spouse", value: "spouse" },
  { label: "Parent", value: "parent" },
  { label: "Sibling", value: "sibling" },
  { label: "Child", value: "child" },
  { label: "Friend", value: "friend" },
  { label: "Other", value: "other" },
];

export const RELIGIONS = [
  { label: "Christianity", value: "christianity" },
  { label: "Islam", value: "islam" },
  { label: "Other", value: "other" },
];

export const NIGERIAN_STATES = [
  { label: "Abia", value: "abia" },
  { label: "Adamawa", value: "adamawa" },
  { label: "Akwa Ibom", value: "akwa_ibom" },
  { label: "Anambra", value: "anambra" },
  { label: "Bauchi", value: "bauchi" },
  { label: "Bayelsa", value: "bayelsa" },
  { label: "Benue", value: "benue" },
  { label: "Borno", value: "borno" },
  { label: "Cross River", value: "cross_river" },
  { label: "Delta", value: "delta" },
  { label: "Ebonyi", value: "ebonyi" },
  { label: "Edo", value: "edo" },
  { label: "Ekiti", value: "ekiti" },
  { label: "Enugu", value: "enugu" },
  { label: "Gombe", value: "gombe" },
  { label: "Imo", value: "imo" },
  { label: "Jigawa", value: "jigawa" },
  { label: "Kaduna", value: "kaduna" },
  { label: "Kano", value: "kano" },
  { label: "Katsina", value: "katsina" },
  { label: "Kebbi", value: "kebbi" },
  { label: "Kogi", value: "kogi" },
  { label: "Kwara", value: "kwara" },
  { label: "Lagos", value: "lagos" },
  { label: "Nasarawa", value: "nasarawa" },
  { label: "Niger", value: "niger" },
  { label: "Ogun", value: "ogun" },
  { label: "Ondo", value: "ondo" },
  { label: "Osun", value: "osun" },
  { label: "Oyo", value: "oyo" },
  { label: "Plateau", value: "plateau" },
  { label: "Rivers", value: "rivers" },
  { label: "Sokoto", value: "sokoto" },
  { label: "Taraba", value: "taraba" },
  { label: "Yobe", value: "yobe" },
  { label: "Zamfara", value: "zamfara" },
];

// Derived from DIAL_CODES — Nigeria first, rest alphabetical, deduplicated by label
const _seen = new Set<string>();
export const COUNTRIES = [
  { label: "Nigeria", value: "Nigeria" },
  ...DIAL_CODES.filter((d) => {
    if (d.label === "Nigeria" || _seen.has(d.label)) return false;
    _seen.add(d.label);
    return true;
  })
    .map((d) => ({ label: d.label, value: d.label }))
    .sort((a, b) => a.label.localeCompare(b.label)),
];

export const SUBSCRIPTION_PLANS = [
  { label: "Basic", value: "basic" },
  { label: "Standard", value: "standard" },
  { label: "Premium", value: "premium" },
  { label: "Enterprise", value: "enterprise" },
  { label: "Custom", value: "custom" },
];

export const TASK_STATUSES = [
  { label: "To Do", value: "to-do" },
  { label: "In Progress", value: "in-progress" },
  { label: "Completed", value: "completed" },
  { label: "Blocked", value: "blocked" },
  { label: "Overdue", value: "overdue" },
];

export const TASK_PRIORITIES = [
  { label: "High", value: "high" },
  { label: "Medium", value: "medium" },
  { label: "Low", value: "low" },
];

export const ACCOUNT_TYPES = [
  { label: "Asset", value: "asset" },
  { label: "Liability", value: "liability" },
  { label: "Equity", value: "equity" },
  { label: "Revenue", value: "revenue" },
  { label: "Expense", value: "expense" },
];

export const EXPENSE_TYPES = [
  { label: "Opex", value: "opex" },
  { label: "Capex", value: "capex" },
  { label: "Service", value: "service" },
  { label: "Travel", value: "travel" },
  { label: "Training", value: "training" },
];

export const LOAN_TYPES = [
  { label: "Personal Loan", value: "personal" },
  { label: "Home Loan", value: "home" },
  { label: "Auto Loan", value: "auto" },
  { label: "Business Loan", value: "business" },
  { label: "Student Loan", value: "student" },
  { label: "Payday Loan", value: "payday" },
];

export const CURRENCIES = [
  { label: "Nigerian Naira", value: "NGN" },
  { label: "US Dollar", value: "USD" },
  { label: "Euro", value: "EUR" },
  { label: "British Pound", value: "GBP" },
  { label: "Japanese Yen", value: "JPY" },
];

export const BACKUP_FREQUENCIES = [
  { label: "Daily", value: "daily" },
  { label: "Weekly", value: "weekly" },
  { label: "Monthly", value: "monthly" },
  { label: "Never", value: "never" },
];

export const DATA_RETENTION_PERIODS = [
  { label: "1 day", value: "1d" },
  { label: "7 days", value: "7d" },
  { label: "30 days", value: "30d" },
  { label: "90 days", value: "90d" },
  { label: "1 year", value: "1y" },
];

export const WORK_TYPES = [
  { label: "On-site", value: "on-site" },
  { label: "Remote", value: "remote" },
  { label: "Hybrid", value: "hybrid" },
];

export const EXPERIENCE_TYPES = [
  { label: "Internship", value: "internship" },
  { label: "Entry Level", value: "entry-level" },
  { label: "Associate Level", value: "associate-level" },
  { label: "Mid Level", value: "mid-level" },
  { label: "Senior Level", value: "senior-level" },
  { label: "Management Level", value: "management-level" },
  { label: "Director Level", value: "director-level" },
  { label: "Executive Level", value: "executive-level" },
];

export const JOB_TYPES = [
  { label: "Full-time", value: "full-time" },
  { label: "Part-time", value: "part-time" },
  { label: "Contract", value: "contract" },
];

export const SALARY_FREQUENCY = [
  { label: "Hourly", value: "hourly" },
  { label: "Daily", value: "daily" },
  { label: "Weekly", value: "weekly" },
  { label: "Monthly", value: "monthly" },
];

export const ROLE_STATUSES = [
  { label: "Active", value: "active" },
  { label: "Pending", value: "pending" },
  { label: "In Review", value: "in-review" },
  { label: "Suspended", value: "suspended" },
  { label: "Archived", value: "archived" },
];

export const SCOPE_TYPES = [
  { label: "Platform", value: "platform" },
  { label: "Tenant", value: "tenant" },
  { label: "Company", value: "company" },
];
